# -*- coding: utf-8 -*-
"""k-means smote.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2RnxGmw9KoOjVeO35t2y0D-Im00bTFD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.neighbors import NearestNeighbors
import warnings
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import pairwise_distances
from imblearn.over_sampling import SMOTE
warnings.filterwarnings('ignore')

np.random.seed(42)

class KMeansSMOTE:
    def __init__(
        self,
        k_clusters=3,
        k_neighbors=5,
        random_state=42,
        verbose=True
    ):
        self.k_clusters = k_clusters
        self.k_neighbors = k_neighbors
        self.random_state = random_state
        self.verbose = verbose

    def fit_resample(self, df, label_col="label_3"):

        # Prepare data
        id_cols = ["user_id", "course_id"]

        feature_cols = [
            c for c in df.columns
            if c not in id_cols + [label_col]
        ]

        X = df[feature_cols].values
        y = df[label_col].astype(str).values

        # Standardize features before clustering and SMOTE
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        # Identify classes and the majority class
        classes, counts = np.unique(
            y,
            return_counts=True
        )

        majority_class = classes[np.argmax(counts)]
        majority_count = counts.max()

        if self.verbose:
            print("\nStarting K-Means SMOTE")
            print(
                f"Majority class: {majority_class} "
                f"({majority_count} samples)"
            )

        # Cluster each minority class using K-Means
        cluster_data = {}

        for cls in classes:

            if cls == majority_class:
                continue

            idx = np.where(y == cls)[0]
            X_cls = X_scaled[idx]

            n_samples = len(X_cls)

            # Use one cluster if the class has fewer than K samples
            if n_samples < self.k_clusters:
                K = 1
            else:
                K = self.k_clusters

            if self.verbose:
                print(
                    f"\nClass {cls}: "
                    f"dividing {n_samples} samples into {K} clusters"
                )

            kmeans = KMeans(
                n_clusters=K,
                init="random",
                n_init=10,
                random_state=self.random_state
            )

            labels = kmeans.fit_predict(X_cls)

            for cluster_id in np.unique(labels):

                X_cluster = X_cls[
                    labels == cluster_id
                ]

                cluster_name = f"{cls}_c{cluster_id}"

                cluster_data[cluster_name] = X_cluster

                if self.verbose:
                    print(
                        f"  - {cluster_name}: "
                        f"{len(X_cluster)} samples"
                    )

        # Generate synthetic samples for each minority class
        new_samples_list = []

        rng = np.random.RandomState(
            self.random_state
        )

        for cls in classes:

            if cls == majority_class:
                continue

            minority_clusters = [
                name
                for name in cluster_data.keys()
                if name.startswith(f"{cls}_")
            ]

            if len(minority_clusters) == 0:
                continue

            # Calculate the number of samples needed to match the majority class
            current_count = np.sum(y == cls)
            n_to_generate = majority_count - current_count

            if n_to_generate <= 0:
                if self.verbose:
                    print(
                        f"\nClass {cls} already has "
                        f"{current_count} samples. "
                        f"No augmentation needed."
                    )
                continue

            # Distribute synthetic samples among clusters
            cluster_sizes = np.array([
                len(cluster_data[c])
                for c in minority_clusters
            ])

            proportions = (
                cluster_sizes /
                cluster_sizes.sum()
            )

            n_generate_clusters = (
                proportions * n_to_generate
            ).astype(int)

            # Correct the rounding difference
            remainder = (
                n_to_generate
                - n_generate_clusters.sum()
            )

            if remainder > 0:
                order = np.argsort(
                    -proportions
                )

                for i in range(remainder):
                    n_generate_clusters[
                        order[i % len(order)]
                    ] += 1

            if self.verbose:
                print(
                    f"\nProcessing minority class {cls}"
                )
                print(
                    f"  Current samples: {current_count}"
                )
                print(
                    f"  Samples to generate: {n_to_generate}"
                )

            # Apply SMOTE within each minority cluster
            for cluster_idx, cluster_name in enumerate(
                minority_clusters
            ):

                X_cluster = cluster_data[
                    cluster_name
                ]

                n_cluster = len(X_cluster)
                n_generate = n_generate_clusters[
                    cluster_idx
                ]

                if n_generate <= 0:
                    continue

                # Skip clusters with fewer than two samples
                if n_cluster < 2:

                    if self.verbose:
                        print(
                            f"  - Skipping {cluster_name}: "
                            f"fewer than 2 samples"
                        )

                    continue

                # Set the effective number of neighbors
                k_eff = min(
                    self.k_neighbors,
                    n_cluster - 1
                )

                if self.verbose:
                    print(
                        f"  - {cluster_name}: "
                        f"{n_cluster} samples -> "
                        f"generating {n_generate} samples "
                        f"(k={k_eff})"
                    )

                synthetic_samples = []

                # Generate synthetic samples using SMOTE interpolation
                for _ in range(n_generate):

                    # Randomly select a minority sample
                    i = rng.randint(
                        0,
                        n_cluster
                    )

                    x_i = X_cluster[i]

                    # Calculate distances to other samples
                    distances = pairwise_distances(
                        x_i.reshape(1, -1),
                        X_cluster
                    )[0]

                    # Select the k nearest neighbors
                    neighbor_indices = np.argsort(
                        distances
                    )[1:k_eff + 1]

                    if len(neighbor_indices) == 0:
                        continue

                    # Randomly select one neighbor
                    j = rng.choice(
                        neighbor_indices
                    )

                    x_j = X_cluster[j]

                    # Generate a synthetic sample
                    lam = rng.uniform(
                        0.0,
                        1.0
                    )

                    x_new = (
                        x_i
                        + lam * (x_j - x_i)
                    )

                    synthetic_samples.append(
                        x_new
                    )

                if len(synthetic_samples) == 0:
                    continue

                # Convert synthetic samples back to the original scale
                X_syn_scaled = np.asarray(
                    synthetic_samples
                )

                X_syn_original = (
                    scaler.inverse_transform(
                        X_syn_scaled
                    )
                )

                # Create a dataframe for synthetic samples
                df_syn = pd.DataFrame(
                    X_syn_original,
                    columns=feature_cols
                )

                df_syn[label_col] = cls

                # Assign existing IDs from the corresponding minority class
                for col in id_cols:

                    if col not in df.columns:
                        continue

                    original_ids = df.loc[
                        df[label_col].astype(str) == cls,
                        col
                    ].values

                    if len(original_ids) > 0:
                        df_syn[col] = rng.choice(
                            original_ids,
                            size=len(df_syn),
                            replace=True
                        )

                new_samples_list.append(
                    df_syn
                )

        # Merge original and synthetic data
        if new_samples_list:

            df_final = pd.concat(
                [df] + new_samples_list,
                axis=0,
                ignore_index=True
            )

            df_final[label_col] = (
                df_final[label_col].astype(int)
            )

            # Shuffle the augmented dataset
            df_final = df_final.sample(
                frac=1,
                random_state=self.random_state
            ).reset_index(drop=True)

            if self.verbose:
                print(
                    "\nK-Means SMOTE completed"
                )

                print(
                    f"Original dataset size: "
                    f"{len(df)}"
                )

                print(
                    f"Augmented dataset size: "
                    f"{len(df_final)}"
                )

                print("\nFinal class distribution:")
                print(
                    df_final[label_col]
                    .value_counts()
                    .sort_index()
                )

            return df_final

        if self.verbose:
            print(
                "\nNo synthetic samples were generated"
            )

        return df.copy()

"""# Median imputation K-Means SMOTE"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/train_median.csv"
LABEL_COL = "label_3"

df_median = pd.read_csv(INPUT_FILE)
print(f"Loaded file: {df_median.shape}")
df_median

# Run CDSMOTE
print(f"Label distribution before K-Means SMOTE:")
print(df_median[LABEL_COL].value_counts().sort_index())

cdsmote = CDSMOTE(verbose=True)
df_balanced = cdsmote.fit_resample(df_median, label_col="label_3")

print(f"\nLabel distribution after K-Means SMOTE:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_median[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="BEFORE K-Means SMOTE", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="AFTER K-Means SMOTE", color='green')
plt.xticks(rotation=45)

plt.suptitle("Label Distribution Comparison - K-Means SMOTE", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_median_k-means smote.parquet", index=False)