# -*- coding: utf-8 -*-
"""k-means smote.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6MRizH1gxtG92Enf1dx7tsd16kgs56q
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.neighbors import NearestNeighbors
import warnings
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import pairwise_distances
from imblearn.over_sampling import SMOTE
warnings.filterwarnings('ignore')

np.random.seed(42)

class CDSMOTE:
    def __init__(self, k_clusters=3, k_neighbors=5, random_state=42, verbose=True):
        self.k_clusters = k_clusters
        self.k_neighbors = k_neighbors
        self.random_state = random_state
        self.verbose = verbose

    def fit_resample(self, df, label_col="label_3"):
        id_cols = ["user_id", "course_id"]
        feature_cols = [c for c in df.columns if c not in id_cols + [label_col]]

        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(df[feature_cols].values)
        y = df[label_col].astype(str).values

        classes, counts = np.unique(y, return_counts=True)
        majority_class = classes[np.argmax(counts)]

        if self.verbose:
            print("\nBắt đầu xử lý dữ liệu")
            print(f"Lớp đa số: {majority_class} ({counts.max()} mẫu)")

        cluster_labels = np.empty(len(y), dtype=object)

        for cls in classes:
            idx = np.where(y == cls)[0]
            n_samples = len(idx)

            if n_samples < self.k_clusters:
                k = 1
            else:
                k = self.k_clusters

            if self.verbose:
                print(f"Lớp {cls} được chia thành {k} cụm")

            kmeans = KMeans(
                n_clusters=k,
                init="random",
                n_init=10,
                random_state=self.random_state
            )
            labels = kmeans.fit_predict(X_scaled[idx])
            unique, counts = np.unique(labels, return_counts=True)

            if self.verbose:
                for u, c in zip(unique, counts):
                    print(f"    Cụm {u}: {c} mẫu")
            for i, lab in enumerate(labels):
                cluster_labels[idx[i]] = f"{cls}_c{lab}"

        unique_clusters, cluster_counts = np.unique(cluster_labels, return_counts=True)

        cluster_data = {uc: X_scaled[cluster_labels == uc] for uc in unique_clusters}
        cluster_sizes = dict(zip(unique_clusters, cluster_counts))

        if self.verbose:
            print("\nDanh sách cụm:")
            for uc in unique_clusters:
                print(f"  - {uc}: {cluster_sizes[uc]} mẫu")

        new_samples_list = []

        max_count = df[label_col].value_counts().max()

        for cls in classes:
            if cls == majority_class:
                continue

            if self.verbose:
                print(f"\nĐang xử lý lớp {cls}")

            min_clusters = [uc for uc in unique_clusters if uc.startswith(f"{cls}_")]
            maj_clusters = [uc for uc in unique_clusters if uc.startswith(f"{majority_class}_")]

            n_clusters_min = len(min_clusters)
            if n_clusters_min == 0: continue

            target_size_per_cluster = max_count // n_clusters_min

            for min_c in min_clusters:
                X_min = cluster_data[min_c]
                n_min = len(X_min)

                if n_min < 2:
                    if self.verbose: print(f"  - Bỏ qua {min_c}: quá ít mẫu")
                    continue

                min_center = np.mean(X_min, axis=0).reshape(1, -1)
                maj_centers = np.array([np.mean(cluster_data[mc], axis=0) for mc in maj_clusters])

                distances = pairwise_distances(min_center, maj_centers)
                closest_idx = np.argmin(distances)
                matched_maj_cluster = maj_clusters[closest_idx]

                X_maj = cluster_data[matched_maj_cluster]
                n_maj = len(X_maj)

                target_size = target_size_per_cluster

                if self.verbose:
                    print(f"\n  - Cụm thiểu số: {min_c} ({n_min} mẫu)")
                    print(f"    Ghép với cụm đa số: {matched_maj_cluster} ({n_maj} mẫu)")
                    print(f"    Target size: {target_size}")

                if target_size <= n_min:
                    continue

                X_sub = np.vstack([X_min, X_maj])
                y_sub = np.array([0] * n_min + [1] * n_maj)

                k_eff = max(1, min(self.k_neighbors, n_min - 1))

                smoter = SMOTE(
                    sampling_strategy={0: target_size},
                    k_neighbors=k_eff,
                    random_state=self.random_state
                )

                try:
                    X_res, y_res = smoter.fit_resample(X_sub, y_sub)
                    if len(X_res) == len(X_sub):
                        if self.verbose:
                            print("    SMOTE không sinh thêm mẫu")
                        continue

                    n_generated = target_size - n_min
                    X_syn_scaled = X_res[len(X_sub): len(X_sub) + n_generated]

                    if len(X_syn_scaled) == 0:
                        continue

                    X_syn_original = scaler.inverse_transform(X_syn_scaled)

                    df_syn = pd.DataFrame(X_syn_original, columns=feature_cols)
                    df_syn[label_col] = cls

                    for col in id_cols:
                        if col in df.columns:
                            original_ids = df[df[label_col].astype(str) == cls][col].values

                            if len(original_ids) == 0:
                                if self.verbose:
                                    print(f"    Bỏ qua gán ID cho {col}: không có dữ liệu")
                                continue

                            df_syn[col] = np.random.choice(original_ids, size=len(df_syn))

                    new_samples_list.append(df_syn)

                    if self.verbose:
                        print(f"    Đã sinh thêm {len(df_syn)} mẫu")

                except Exception as e:
                    if self.verbose:
                        print(f"    Lỗi khi sinh mẫu: {e}")
                    continue

        if new_samples_list:
            df_final = pd.concat([df] + new_samples_list, axis=0, ignore_index=True)

            df_final[LABEL_COL] = df_final[LABEL_COL].astype(int)

            if self.verbose:
                print("\nHoàn tất tăng cường dữ liệu")
                print(f"Tổng số mẫu sau cùng: {len(df_final)}")

            return df_final.sample(frac=1, random_state=self.random_state).reset_index(drop=True)

        if self.verbose:
            print("\nKhông có mẫu nào được sinh thêm")

        return df.copy()

"""# Median imputation K-Means SMOTE"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/train_median.csv"
LABEL_COL = "label_3"

df_median = pd.read_csv(INPUT_FILE)
print(f"Đã đọc file: {df_median.shape}")
df_median

# Chạy cdsmote
print(f"Phân bố label trước K-Means SMOTE:")
print(df_median[LABEL_COL].value_counts().sort_index())

cdsmote = CDSMOTE(verbose=True)
df_balanced = cdsmote.fit_resample(df_median, label_col="label_3")

print(f"\nPhân bố label sau K-Means SMOTE:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_median[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC K-Means SMOTE", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU K-Means SMOTE", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label - K-Means SMOTE", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_median_k-means smote.parquet", index=False)

"""# Mean imputation K-Means SMOTE"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Mean/Mean/train_mean.csv"
LABEL_COL = "label_3"

df_mean = pd.read_csv(INPUT_FILE)
print(f"Đã đọc file: {df_mean.shape}")
df_mean

# Chạy K-Means Smote
print(f"Phân bố label trước K-Means SMOTE:")
print(df_mean[LABEL_COL].value_counts().sort_index())

cdsmote = CDSMOTE(verbose=True)
df_balanced = cdsmote.fit_resample(df_mean, label_col="label_3")

print(f"\nPhân bố label sau K-Means SMOTE:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_mean[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC K-Means SMOTE", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU K-Means SMOTE", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label - K-Means SMOTE", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_mean_k-means smote.parquet", index=False)

"""# Extra_trees imputation K-Means SMOTE"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Extra_trees/Extra_trees/train_extra.csv"
LABEL_COL = "label_3"

df_Extra_trees = pd.read_csv(INPUT_FILE)
print(f"Đã đọc file: {df_Extra_trees.shape}")
df_Extra_trees

# Chạy cdsmote
print(f"Phân bố label trước K-Means SMOTE:")
print(df_Extra_trees[LABEL_COL].value_counts().sort_index())

cdsmote = CDSMOTE(verbose=True)
df_balanced = cdsmote.fit_resample(df_Extra_trees, label_col="label_3")

print(f"\nPhân bố label sau K-Means SMOTE:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_Extra_trees[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC K-Means SMOTE", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU K-Means SMOTE", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label - K-Means SMOTE", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_Extra_trees_k-means smote.parquet", index=False)