# -*- coding: utf-8 -*-
"""ksgan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ntJSxd8b5khwRDwrueFC1iqRh39m27m
"""

import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

def get_generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace=True),
    )

class Generator(nn.Module):
    def __init__(self, z_dim, im_dim, hidden_dim=128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            get_generator_block(z_dim, hidden_dim),
            get_generator_block(hidden_dim, hidden_dim * 2),
            get_generator_block(hidden_dim * 2, hidden_dim * 4),
            get_generator_block(hidden_dim * 4, hidden_dim * 8),
            nn.Linear(hidden_dim * 8, im_dim),
            nn.Sigmoid()
        )
    def forward(self, x): return self.gen(x)

def get_discriminator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.LeakyReLU(0.2, inplace=True)
    )

class Discriminator(nn.Module):
    def __init__(self, im_dim, hidden_dim=128):
        super(Discriminator, self).__init__()
        self.disc = nn.Sequential(
            get_discriminator_block(im_dim, hidden_dim * 4),
            get_discriminator_block(hidden_dim * 4, hidden_dim * 2),
            get_discriminator_block(hidden_dim * 2, hidden_dim),
            nn.Linear(hidden_dim, 1)
        )
    def forward(self, x): return self.disc(x)

class KSGAN:
    def __init__(self, k_clusters=3, k_neighbors=5, random_state=42, verbose=True):
        self.k_clusters = k_clusters
        self.k_neighbors = k_neighbors
        self.random_state = random_state
        self.verbose = verbose
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'

    def fit_resample(self, df, label_col="label_3", epochs=50, batch_size=512, lr=0.0001):
        id_cols = ["user_id", "course_id"]
        feature_cols = [c for c in df.columns if c not in id_cols + [label_col]]
        n_features = len(feature_cols)

        # ===== 0. CHUẨN HÓA =====
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(df[feature_cols].values)
        y = df[label_col].astype(str).values

        classes, counts = np.unique(y, return_counts=True)
        majority_class = classes[np.argmax(counts)]

        if self.verbose:
            print("\nBắt đầu xử lý dữ liệu (CDSMOTE + GAN Refiner)")
            print(f"Lớp đa số: {majority_class} ({counts.max()} mẫu)")

        cluster_labels = np.empty(len(y), dtype=object)
        for cls in classes:
            idx = np.where(y == cls)[0]
            n_samples = len(idx)
            k = self.k_clusters if n_samples >= self.k_clusters else 1

            if self.verbose:
                print(f"Lớp {cls} được chia thành {k} cụm")

            kmeans = KMeans(n_clusters=k, init="random", n_init=10, random_state=self.random_state)
            labels = kmeans.fit_predict(X_scaled[idx])
            for i, lab in enumerate(labels):
                cluster_labels[idx[i]] = f"{cls}_c{lab}"

        unique_clusters = np.unique(cluster_labels)
        cluster_data = {uc: X_scaled[cluster_labels == uc] for uc in unique_clusters}

        new_samples_list = []
        max_count = df[label_col].value_counts().max()

        for cls in classes:
            if cls == majority_class: continue

            if self.verbose: print(f"\nĐang xử lý lớp {cls}")

            min_clusters = [uc for uc in unique_clusters if uc.startswith(f"{cls}_")]
            maj_clusters = [uc for uc in unique_clusters if uc.startswith(f"{majority_class}_")]
            n_clusters_min = len(min_clusters)
            if n_clusters_min == 0: continue

            target_size_per_cluster = max_count // n_clusters_min

            for min_c in min_clusters:
                X_min = cluster_data[min_c]
                n_min = len(X_min)
                if n_min < 2: continue

                min_center = np.mean(X_min, axis=0).reshape(1, -1)
                maj_centers = np.array([np.mean(cluster_data[mc], axis=0) for mc in maj_clusters])
                distances = pairwise_distances(min_center, maj_centers)
                matched_maj_cluster = maj_clusters[np.argmin(distances)]

                X_maj = cluster_data[matched_maj_cluster]
                target_size = target_size_per_cluster

                if self.verbose:
                    print(f"  - Cụm: {min_c} ({n_min} mẫu) ghép với {matched_maj_cluster}")

                if target_size <= n_min: continue

                X_sub = np.vstack([X_min, X_maj])
                y_sub = np.array([0] * n_min + [1] * len(X_maj))
                k_eff = max(1, min(self.k_neighbors, n_min - 1))

                smoter = SMOTE(sampling_strategy={0: target_size}, k_neighbors=k_eff, random_state=self.random_state)

                try:
                    X_res, _ = smoter.fit_resample(X_sub, y_sub)
                    X_seed_samples = X_res[len(X_sub):]
                    if len(X_seed_samples) == 0: continue

                    local_mms = MinMaxScaler()
                    X_real_norm = torch.FloatTensor(local_mms.fit_transform(X_min)).to(self.device)
                    X_seed_norm = torch.FloatTensor(local_mms.transform(X_seed_samples)).to(self.device)

                    gen = Generator(z_dim=n_features, im_dim=n_features).to(self.device)
                    disc = Discriminator(im_dim=n_features).to(self.device)
                    gen_opt = torch.optim.Adam(gen.parameters(), lr=lr)
                    disc_opt = torch.optim.Adam(disc.parameters(), lr=lr)
                    criterion = nn.BCEWithLogitsLoss()

                    dataloader = DataLoader(TensorDataset(X_real_norm), batch_size=batch_size, shuffle=True)

                    gen.train(); disc.train()
                    for epoch in range(epochs):
                        for real_batch in dataloader:
                            real = real_batch[0]; curr_bs = len(real)
                            idx = torch.randint(0, len(X_seed_norm), (curr_bs,))
                            batch_seeds = X_seed_norm[idx]

                            disc_opt.zero_grad()
                            fake = gen(batch_seeds)
                            loss_d = (criterion(disc(real), torch.ones(curr_bs, 1).to(self.device)) +
                                      criterion(disc(fake.detach()), torch.zeros(curr_bs, 1).to(self.device))) / 2
                            loss_d.backward(); disc_opt.step()

                            gen_opt.zero_grad()
                            loss_g = criterion(disc(fake), torch.ones(curr_bs, 1).to(self.device))
                            loss_g.backward(); gen_opt.step()

                    gen.eval()
                    with torch.no_grad():
                        refined_norm = gen(X_seed_norm).cpu().numpy()

                    X_syn_scaled = local_mms.inverse_transform(refined_norm)
                    X_syn_original = scaler.inverse_transform(X_syn_scaled)

                    df_syn = pd.DataFrame(X_syn_original, columns=feature_cols)
                    df_syn[label_col] = cls

                    for col in id_cols:
                        if col in df.columns:
                            original_ids = df[df[label_col].astype(str) == cls][col].values
                            df_syn[col] = np.random.choice(original_ids, size=len(df_syn))

                    new_samples_list.append(df_syn)
                    if self.verbose: print(f"    GAN đã tinh chỉnh xong {len(df_syn)} mẫu")

                except Exception as e:
                    if self.verbose: print(f"    Lỗi tại cụm {min_c}: {e}")

        if new_samples_list:
            df_final = pd.concat([df] + new_samples_list, axis=0, ignore_index=True)
            try:
                df_final[label_col] = df_final[label_col].astype(float).astype(int)
            except: pass

            if self.verbose:
                print(f"\nHoàn tất. Tổng số mẫu sau cùng: {len(df_final)}")
            return df_final.sample(frac=1, random_state=self.random_state).reset_index(drop=True)

        return df.copy()

"""# Median imputation KSGAN"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/train_median.parquet"
LABEL_COL = "label_3"

df_median = pd.read_parquet(INPUT_FILE)
print(f"Đã đọc file: {df_median.shape}")
df_median

print(f"Phân bố label trước KSGAN:")
print(df_median[LABEL_COL].value_counts().sort_index())

ksgan = KSGAN(verbose=True)
df_balanced = ksgan.fit_resample(df_median, label_col="label_3")

print(f"\nPhân bố label sau KSGAN:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_median[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC KSGAN", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU KSGAN", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label KSGAN", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_median_cdsmote_gan.parquet", index=False)

"""# Mean imputation KSGAN"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Mean/Mean/train_mean.parquet"
LABEL_COL = "label_3"

df_mean = pd.read_parquet(INPUT_FILE)
print(f"Đã đọc file: {df_mean.shape}")
df_mean

print(f"Phân bố label trước KSGAN:")
print(df_mean[LABEL_COL].value_counts().sort_index())

ksgan = KSGAN(verbose=True)
df_balanced = ksgan.fit_resample(df_mean, label_col="label_3")

print(f"\nPhân bố label sau KSGAN:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_mean[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC KSGAN", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU KSGAN", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label KSGAN", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_mean_cdsmote_gan.parquet", index=False)

"""# Extra_trees imputation KSGAN"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Extra_trees/Extra_trees/train_extra.parquet"
LABEL_COL = "label_3"

df_Extra_trees = pd.read_parquet(INPUT_FILE)
print(f"Đã đọc file: {df_Extra_trees.shape}")
df_Extra_trees

print(f"Phân bố label trước KSGAN:")
print(df_Extra_trees[LABEL_COL].value_counts().sort_index())

ksgan = KSGAN(verbose=True)
df_balanced = ksgan.fit_resample(df_Extra_trees, label_col="label_3")

print(f"\nPhân bố label sau KSGAN:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_Extra_trees[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC KSGAN", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU KSGAN", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label KSGAN", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_Extra_trees_cdsmote_gan.parquet", index=False)