# -*- coding: utf-8 -*-
"""ksgan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_BN8fvhHYLTit5zVXi0ElBEAd4Vv3tX
"""

import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')


def get_generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace=True),
    )


class Generator(nn.Module):
    def __init__(self, z_dim, im_dim, hidden_dim=128):
        super(Generator, self).__init__()
        self.gen = nn.Sequential(
            get_generator_block(z_dim, hidden_dim),
            get_generator_block(hidden_dim, hidden_dim * 2),
            get_generator_block(hidden_dim * 2, hidden_dim * 4),
            get_generator_block(hidden_dim * 4, hidden_dim * 8),
            nn.Linear(hidden_dim * 8, im_dim),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.gen(x)


def get_discriminator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.LeakyReLU(0.2, inplace=True)
    )


class Discriminator(nn.Module):
    def __init__(self, im_dim, hidden_dim=128):
        super(Discriminator, self).__init__()
        self.disc = nn.Sequential(
            get_discriminator_block(im_dim, hidden_dim * 4),
            get_discriminator_block(hidden_dim * 4, hidden_dim * 2),
            get_discriminator_block(hidden_dim * 2, hidden_dim),
            nn.Linear(hidden_dim, 1)
        )

    def forward(self, x):
        return self.disc(x)


class KSGAN:
    def __init__(
        self,
        k_clusters=3,
        k_neighbors=5,
        random_state=42,
        verbose=True
    ):
        self.k_clusters = k_clusters
        self.k_neighbors = k_neighbors
        self.random_state = random_state
        self.verbose = verbose
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'

    def fit_resample(
        self,
        df,
        label_col="label_3",
        epochs=50,
        batch_size=512,
        lr=0.0001
    ):
        id_cols = ["user_id", "course_id"]

        feature_cols = [
            c for c in df.columns
            if c not in id_cols + [label_col]
        ]

        n_features = len(feature_cols)

        # Standardize features
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(
            df[feature_cols].values
        )

        y = df[label_col].astype(str).values

        classes, counts = np.unique(
            y,
            return_counts=True
        )

        majority_class = classes[np.argmax(counts)]
        majority_count = counts.max()

        if self.verbose:
            print("\nStarting KSGAN")
            print(
                f"Majority class: "
                f"{majority_class} "
                f"({majority_count} samples)"
            )

        # Cluster each minority class using K-Means
        cluster_data = {}

        for cls in classes:

            if cls == majority_class:
                continue

            idx = np.where(y == cls)[0]

            X_cls = X_scaled[idx]
            n_samples = len(X_cls)

            if n_samples < self.k_clusters:
                k = 1
            else:
                k = self.k_clusters

            if self.verbose:
                print(
                    f"\nClass {cls}: "
                    f"dividing {n_samples} samples "
                    f"into {k} clusters"
                )

            kmeans = KMeans(
                n_clusters=k,
                init="random",
                n_init=10,
                random_state=self.random_state
            )

            cluster_labels = kmeans.fit_predict(X_cls)

            for cluster_id in np.unique(cluster_labels):

                X_cluster = X_cls[
                    cluster_labels == cluster_id
                ]

                cluster_name = (
                    f"{cls}_c{cluster_id}"
                )

                cluster_data[cluster_name] = X_cluster

                if self.verbose:
                    print(
                        f"  - {cluster_name}: "
                        f"{len(X_cluster)} samples"
                    )

        new_samples_list = []

        rng = np.random.RandomState(
            self.random_state
        )

        # Generate synthetic samples for each minority class
        for cls in classes:

            if cls == majority_class:
                continue

            minority_clusters = [
                name
                for name in cluster_data.keys()
                if name.startswith(f"{cls}_")
            ]

            if len(minority_clusters) == 0:
                continue

            current_count = np.sum(y == cls)

            n_to_generate = (
                majority_count - current_count
            )

            if n_to_generate <= 0:
                if self.verbose:
                    print(
                        f"\nClass {cls} already has "
                        f"{current_count} samples. "
                        f"No augmentation needed."
                    )
                continue

            # Distribute synthetic samples according to cluster size
            cluster_sizes = np.array([
                len(cluster_data[c])
                for c in minority_clusters
            ])

            proportions = (
                cluster_sizes /
                cluster_sizes.sum()
            )

            n_generate_clusters = (
                proportions * n_to_generate
            ).astype(int)

            # Correct rounding differences
            remainder = (
                n_to_generate
                - n_generate_clusters.sum()
            )

            if remainder > 0:

                order = np.argsort(
                    -proportions
                )

                for i in range(remainder):
                    n_generate_clusters[
                        order[i % len(order)]
                    ] += 1

            if self.verbose:
                print(
                    f"\nProcessing minority class {cls}"
                )
                print(
                    f"  Current samples: "
                    f"{current_count}"
                )
                print(
                    f"  Samples to generate: "
                    f"{n_to_generate}"
                )

            # Process each minority cluster
            for cluster_idx, cluster_name in enumerate(
                minority_clusters
            ):

                X_min = cluster_data[
                    cluster_name
                ]

                n_min = len(X_min)

                n_generate = n_generate_clusters[
                    cluster_idx
                ]

                if n_generate <= 0:
                    continue

                # Skip clusters with fewer than two samples
                if n_min < 2:

                    if self.verbose:
                        print(
                            f"  - Skipping {cluster_name}: "
                            f"fewer than 2 samples"
                        )

                    continue

                k_eff = max(
                    1,
                    min(
                        self.k_neighbors,
                        n_min - 1
                    )
                )

                if self.verbose:
                    print(
                        f"  - {cluster_name}: "
                        f"{n_min} samples -> "
                        f"generating {n_generate} "
                        f"samples (k={k_eff})"
                    )

                # Generate K-Means SMOTE seed samples
                try:

                    if n_generate > 0:

                        smoter = SMOTE(
                            sampling_strategy={
                                0: n_min + n_generate
                            },
                            k_neighbors=k_eff,
                            random_state=self.random_state
                        )

                        y_min = np.zeros(
                            n_min,
                            dtype=int
                        )

                        X_res, _ = smoter.fit_resample(
                            X_min,
                            y_min
                        )

                        X_seed_samples = X_res[
                            n_min:
                        ]

                        if len(X_seed_samples) == 0:
                            continue

                    # Normalize real and seed samples for GAN
                    local_mms = MinMaxScaler()

                    X_real_norm = torch.FloatTensor(
                        local_mms.fit_transform(X_min)
                    ).to(self.device)

                    X_seed_norm = torch.FloatTensor(
                        local_mms.transform(
                            X_seed_samples
                        )
                    ).to(self.device)

                    # Initialize GAN
                    gen = Generator(
                        z_dim=n_features,
                        im_dim=n_features
                    ).to(self.device)

                    disc = Discriminator(
                        im_dim=n_features
                    ).to(self.device)

                    gen_opt = torch.optim.Adam(
                        gen.parameters(),
                        lr=lr
                    )

                    disc_opt = torch.optim.Adam(
                        disc.parameters(),
                        lr=lr
                    )

                    criterion = nn.BCEWithLogitsLoss()

                    dataloader = DataLoader(
                        TensorDataset(X_real_norm),
                        batch_size=batch_size,
                        shuffle=True
                    )

                    gen.train()
                    disc.train()

                    # Train GAN to refine K-Means SMOTE samples
                    for epoch in range(epochs):

                        for real_batch in dataloader:

                            real = real_batch[0]
                            curr_bs = len(real)

                            idx = torch.randint(
                                0,
                                len(X_seed_norm),
                                (curr_bs,),
                                device=self.device
                            )

                            batch_seeds = (
                                X_seed_norm[idx]
                            )

                            # Train discriminator
                            disc_opt.zero_grad()

                            fake = gen(batch_seeds)

                            real_labels = torch.ones(
                                curr_bs,
                                1,
                                device=self.device
                            )

                            fake_labels = torch.zeros(
                                curr_bs,
                                1,
                                device=self.device
                            )

                            loss_d = (
                                criterion(
                                    disc(real),
                                    real_labels
                                )
                                +
                                criterion(
                                    disc(fake.detach()),
                                    fake_labels
                                )
                            ) / 2

                            loss_d.backward()
                            disc_opt.step()

                            # Train generator
                            gen_opt.zero_grad()

                            loss_g = criterion(
                                disc(fake),
                                real_labels
                            )

                            loss_g.backward()
                            gen_opt.step()

                    # Generate refined samples
                    gen.eval()

                    with torch.no_grad():
                        refined_norm = (
                            gen(X_seed_norm)
                            .cpu()
                            .numpy()
                        )

                    # Convert generated samples back to original scale
                    X_syn_scaled = (
                        local_mms.inverse_transform(
                            refined_norm
                        )
                    )

                    X_syn_original = (
                        scaler.inverse_transform(
                            X_syn_scaled
                        )
                    )

                    # Create dataframe for synthetic samples
                    df_syn = pd.DataFrame(
                        X_syn_original,
                        columns=feature_cols
                    )

                    df_syn[label_col] = cls

                    # Assign existing IDs from the minority class
                    for col in id_cols:

                        if col in df.columns:

                            original_ids = df.loc[
                                df[label_col].astype(str) == cls,
                                col
                            ].values

                            if len(original_ids) > 0:
                                df_syn[col] = rng.choice(
                                    original_ids,
                                    size=len(df_syn),
                                    replace=True
                                )

                    new_samples_list.append(
                        df_syn
                    )

                    if self.verbose:
                        print(
                            f"    GAN refined "
                            f"{len(df_syn)} samples"
                        )

                except Exception as e:

                    if self.verbose:
                        print(
                            f"    Error in "
                            f"{cluster_name}: {e}"
                        )

        # Merge original and synthetic data
        if new_samples_list:

            df_final = pd.concat(
                [df] + new_samples_list,
                axis=0,
                ignore_index=True
            )

            try:
                df_final[label_col] = (
                    df_final[label_col]
                    .astype(float)
                    .astype(int)
                )
            except:
                pass

            if self.verbose:

                print(
                    f"\nKSGAN completed"
                )

                print(
                    f"Original dataset size: "
                    f"{len(df)}"
                )

                print(
                    f"Final dataset size: "
                    f"{len(df_final)}"
                )

                print(
                    "\nFinal class distribution:"
                )

                print(
                    df_final[label_col]
                    .value_counts()
                    .sort_index()
                )

            return (
                df_final
                .sample(
                    frac=1,
                    random_state=self.random_state
                )
                .reset_index(drop=True)
            )

        if self.verbose:
            print(
                "\nNo synthetic samples were generated"
            )

        return df.copy()

"""# Median imputation KSGAN"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/train_median.parquet"
LABEL_COL = "label_3"

df_median = pd.read_parquet(INPUT_FILE)
print(f"Loaded file: {df_median.shape}")
df_median

print(f"Label distribution before KSGAN:")
print(df_median[LABEL_COL].value_counts().sort_index())

ksgan = KSGAN(verbose=True)
df_balanced = ksgan.fit_resample(df_median, label_col="label_3")

print(f"\nLabel distribution after KSGAN:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
df_median[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="BEFORE KSGAN", color='red')
plt.xticks(rotation=45)
plt.subplot(1,2,2)

df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="AFTER KSGAN", color='green')
plt.xticks(rotation=45)
plt.suptitle("Label Distribution Comparison - KSGAN", fontsize=14)

plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_median_k-means smote_gan.parquet", index=False)