# -*- coding: utf-8 -*-
"""smote.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16s907CPuhZ1n6nocB4aT5GJAZ7EoMmna
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings("ignore")


class PureSMOTE:

    def __init__(
        self,
        k_neighbors=5,
        random_state=42,
        verbose=True
    ):

        self.k_neighbors = k_neighbors
        self.random_state = random_state
        self.verbose = verbose

    def fit_resample(self, df, label_col="label_3"):
        np.random.seed(self.random_state)

        id_cols = ["user_id", "course_id"]
        feature_cols = [c for c in df.columns if c not in id_cols + [label_col]]

        # Scaling
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(df[feature_cols].values)
        y = df[label_col].values

        if self.verbose:
            print("\nSMOTE:")
            print("\nClass distribution BEFORE:")
            print(pd.Series(y).value_counts().sort_index())

        # SMOTE
        smoter = SMOTE(
            sampling_strategy='not majority',
            k_neighbors=self.k_neighbors,
            random_state=self.random_state
        )
        X_resampled, y_resampled = smoter.fit_resample(X_scaled, y)

        # Inverse transform
        X_original = scaler.inverse_transform(X_resampled)

        df_final = pd.DataFrame(X_original, columns=feature_cols)
        df_final[label_col] = y_resampled

        original_size = len(df)
        n_new = len(df_final) - original_size

        if n_new > 0:
            synthetic_labels = y_resampled[original_size:]
            syn_ids = {col: [] for col in id_cols if col in df.columns}

            unique_syn_cls, counts_syn_cls = np.unique(synthetic_labels, return_counts=True)
            syn_counts_dict = dict(zip(unique_syn_cls, counts_syn_cls))

            grouped_ids = {}
            for col in syn_ids.keys():
                grouped_ids[col] = df.groupby(label_col)[col].apply(lambda x: x.values).to_dict()

            syn_ids_sampled = {col: [] for col in syn_ids.keys()}

            for cls in unique_syn_cls:
                n_samples_needed = syn_counts_dict[cls]
                for col in syn_ids.keys():
                    available_ids = grouped_ids[col][cls]
                    sampled_values = np.random.choice(available_ids, size=n_samples_needed, replace=True)
                    syn_ids_sampled[col].append(sampled_values)

            for col in syn_ids.keys():
                original_ids = df[col].values
                synthetic_col_values = np.concatenate(syn_ids_sampled[col])
                df_final[col] = np.concatenate([original_ids, synthetic_col_values])
            # --------------------------------

        if self.verbose:
            print("\nClass distribution AFTER:")
            print(df_final[label_col].value_counts().sort_index())
            print(f"\nTotal samples: {len(df_final)}")

        return df_final.sample(frac=1, random_state=self.random_state).reset_index(drop=True)

"""# Median imputation"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/train_median.parquet"
LABEL_COL = "label_3"

df_median = pd.read_parquet(INPUT_FILE)
print(f"Đã đọc file: {df_median.shape}")
df_median

print(f"Phân bố label trước SMOTE:")
print(df_median[LABEL_COL].value_counts().sort_index())

pure_smote = PureSMOTE(verbose=True, random_state=42)

df_balanced = pure_smote.fit_resample(df_median, label_col="label_3")

print(f"\nPhân bố label sau SMOTE:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_median[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC SMOTE", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU SMOTE", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label - SMOTE", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_median_smote.parquet", index=False)

"""# Mean imputation"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Mean/Mean/train_mean.parquet"
LABEL_COL = "label_3"

df_mean = pd.read_parquet(INPUT_FILE)
print(f"Đã đọc file: {df_mean.shape}")
df_mean

print(f"Phân bố label trước SMOTE:")
print(df_mean[LABEL_COL].value_counts().sort_index())

pure_smote = PureSMOTE(verbose=True, random_state=42)

df_balanced = pure_smote.fit_resample(df_mean, label_col="label_3")

print(f"\nPhân bố label sau SMOTE:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_mean[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC SMOTE", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU SMOTE", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label - SMOTE", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_mean_smote.parquet", index=False)

"""# Extra_trees imputation"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Extra_trees/Extra_trees/train_extra.parquet"
LABEL_COL = "label_3"

df_Extra_trees = pd.read_parquet(INPUT_FILE)
print(f"Đã đọc file: {df_Extra_trees.shape}")
df_Extra_trees

print(f"Phân bố label trước SMOTE:")
print(df_Extra_trees[LABEL_COL].value_counts().sort_index())

pure_smote = PureSMOTE(verbose=True, random_state=42)

df_balanced = pure_smote.fit_resample(df_Extra_trees, label_col="label_3")

print(f"\nPhân bố label sau SMOTE:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_Extra_trees[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC SMOTE", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU SMOTE", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label - SMOTE", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_extra_smote.parquet", index=False)