# -*- coding: utf-8 -*-
"""smotified_gan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rzCfduQvYPyBeGdleVXJa-RnXN7DJmZi
"""

import numpy as np
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from imblearn.over_sampling import SMOTE
import warnings
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")


# Generator
def get_generator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.BatchNorm1d(output_dim),
        nn.ReLU(inplace=True),
    )


class Generator(nn.Module):
    def __init__(self, z_dim, im_dim, hidden_dim=128):
        super(Generator, self).__init__()

        self.gen = nn.Sequential(
            get_generator_block(z_dim, hidden_dim),
            get_generator_block(hidden_dim, hidden_dim * 2),
            get_generator_block(hidden_dim * 2, hidden_dim * 4),
            get_generator_block(hidden_dim * 4, hidden_dim * 8),
            nn.Linear(hidden_dim * 8, im_dim),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.gen(x)


# Discriminator
def get_discriminator_block(input_dim, output_dim):
    return nn.Sequential(
        nn.Linear(input_dim, output_dim),
        nn.LeakyReLU(0.2, inplace=True)
    )


class Discriminator(nn.Module):
    def __init__(self, im_dim, hidden_dim=128):
        super(Discriminator, self).__init__()

        self.disc = nn.Sequential(
            get_discriminator_block(im_dim, hidden_dim * 4),
            get_discriminator_block(hidden_dim * 4, hidden_dim * 2),
            get_discriminator_block(hidden_dim * 2, hidden_dim),
            nn.Linear(hidden_dim, 1)
        )

    def forward(self, x):
        return self.disc(x)


# SMOTified-GAN (Multi-class Extension)
class SMOTifiedGAN:

    def __init__(
        self,
        k_neighbors=5,
        random_state=42,
        verbose=True
    ):

        self.k_neighbors = k_neighbors
        self.random_state = random_state
        self.verbose = verbose

        self.device = (
            "cuda"
            if torch.cuda.is_available()
            else "cpu"
        )

    def fit_resample(
        self,
        df,
        label_col="label_3",
        epochs=50,
        batch_size=512,
        lr=0.0001
    ):

        np.random.seed(self.random_state)
        torch.manual_seed(self.random_state)

        # Column handling
        id_cols = ["user_id", "course_id"]

        feature_cols = [
            c for c in df.columns
            if c not in id_cols + [label_col]
        ]

        n_features = len(feature_cols)

        # Standard Scaling
        scaler = StandardScaler()

        X_scaled = scaler.fit_transform(
            df[feature_cols].values
        )

        y = df[label_col].astype(str).values

        # Class statistics
        classes, counts = np.unique(y, return_counts=True)

        majority_class = classes[np.argmax(counts)]

        max_count = counts.max()

        minority_classes = [
            cls for cls in classes
            if cls != majority_class
        ]

        if self.verbose:
            print("\n========== SMOTified-GAN ==========")
            print(f"Device: {self.device}")
            print(f"Majority class: {majority_class}")
            print("\nClass distribution BEFORE:")

            for cls, cnt in zip(classes, counts):
                print(f"Class {cls}: {cnt}")

        # Store generated samples
        synthetic_dfs = []

        # Process each minority class independently
        for cls in minority_classes:

            if self.verbose:
                print(f"\n===================================")
                print(f"Processing minority class {cls}")

            # Extract minority + majority
            X_min = X_scaled[y == cls]

            X_maj = X_scaled[y == majority_class]

            n_min = len(X_min)
            n_maj = len(X_maj)

            if self.verbose:
                print(f"Minority samples : {n_min}")
                print(f"Majority samples : {n_maj}")

            if n_min < 2:
                print(f"Skip class {cls} (too few samples)")
                continue

            # Prepare SMOTE dataset
            # minority = 0
            # majority = 1
            X_sub = np.vstack([X_min, X_maj])

            y_sub = np.array(
                [0] * n_min +
                [1] * n_maj
            )

            # SMOTE
            k_eff = max(
                1,
                min(self.k_neighbors, n_min - 1)
            )

            smoter = SMOTE(
                sampling_strategy='not majority',
                k_neighbors=k_eff,
                random_state=self.random_state
            )

            X_res, y_res = smoter.fit_resample(
                X_sub,
                y_sub
            )


            X_seed_samples = X_res[len(X_sub):]

            if len(X_seed_samples) == 0:
                print("No SMOTE samples generated")
                continue

            if self.verbose:
                print(f"SMOTE generated: {len(X_seed_samples)} samples")

            # Local MinMax scaling for GAN
            local_mms = MinMaxScaler()

            X_real_norm = local_mms.fit_transform(X_min)

            X_seed_norm = local_mms.transform(
                X_seed_samples
            )

            X_real_tensor = torch.FloatTensor(
                X_real_norm
            ).to(self.device)

            X_seed_tensor = torch.FloatTensor(
                X_seed_norm
            ).to(self.device)

            # GAN
            gen = Generator(
                z_dim=n_features,
                im_dim=n_features
            ).to(self.device)

            disc = Discriminator(
                im_dim=n_features
            ).to(self.device)

            gen_opt = torch.optim.Adam(
                gen.parameters(),
                lr=lr
            )

            disc_opt = torch.optim.Adam(
                disc.parameters(),
                lr=lr
            )

            criterion = nn.BCEWithLogitsLoss()

            # Real minority dataloader
            dataloader = DataLoader(
                TensorDataset(X_real_tensor),
                batch_size=batch_size,
                shuffle=True
            )

            # TRAIN GAN
            gen.train()
            disc.train()

            for epoch in range(epochs):

                epoch_g_loss = 0
                epoch_d_loss = 0

                for real_batch in dataloader:

                    real = real_batch[0]

                    curr_bs = len(real)

                    idx = torch.randint(
                        0,
                        len(X_seed_tensor),
                        (curr_bs,)
                    )

                    batch_seeds = X_seed_tensor[idx]

                    # Train Discriminator
                    disc_opt.zero_grad()

                    fake = gen(batch_seeds)

                    real_labels = torch.ones(
                        curr_bs,
                        1
                    ).to(self.device)

                    fake_labels = torch.zeros(
                        curr_bs,
                        1
                    ).to(self.device)

                    disc_real_pred = disc(real)

                    disc_fake_pred = disc(
                        fake.detach()
                    )

                    disc_real_loss = criterion(
                        disc_real_pred,
                        real_labels
                    )

                    disc_fake_loss = criterion(
                        disc_fake_pred,
                        fake_labels
                    )

                    disc_loss = (
                        disc_real_loss +
                        disc_fake_loss
                    ) / 2

                    disc_loss.backward()

                    disc_opt.step()

                    # Train Generator
                    gen_opt.zero_grad()

                    fake = gen(batch_seeds)

                    disc_fake_pred = disc(fake)

                    gen_loss = criterion(
                        disc_fake_pred,
                        real_labels
                    )

                    gen_loss.backward()

                    gen_opt.step()

                    epoch_g_loss += gen_loss.item()
                    epoch_d_loss += disc_loss.item()

                # Logging
                if self.verbose and (
                    epoch == 0 or
                    (epoch + 1) % 10 == 0
                ):
                    print(
                        f"Epoch [{epoch+1}/{epochs}] | "
                        f"G Loss: {epoch_g_loss:.4f} | "
                        f"D Loss: {epoch_d_loss:.4f}"
                    )

            # Generate refined samples
            gen.eval()

            with torch.no_grad():

                refined_norm = gen(
                    X_seed_tensor
                ).cpu().numpy()

            # Inverse transform
            refined_scaled = local_mms.inverse_transform(
                refined_norm
            )

            refined_original = scaler.inverse_transform(
                refined_scaled
            )

            # Create synthetic dataframe
            df_syn = pd.DataFrame(
                refined_original,
                columns=feature_cols
            )

            df_syn[label_col] = cls

            # Recreate ID columns
            for col in id_cols:

                if col in df.columns:

                    original_ids = df[
                        df[label_col].astype(str) == cls
                    ][col].values

                    df_syn[col] = np.random.choice(
                        original_ids,
                        size=len(df_syn)
                    )

            synthetic_dfs.append(df_syn)

            if self.verbose:
                print(
                    f"GAN refined {len(df_syn)} samples "
                    f"for class {cls}"
                )

        # Merge final dataset
        if synthetic_dfs:

            df_final = pd.concat(
                [df] + synthetic_dfs,
                axis=0,
                ignore_index=True
            )

            try:
                df_final[label_col] = (
                    df_final[label_col]
                    .astype(float)
                    .astype(int)
                )
            except:
                pass

            if self.verbose:

                print("\n===================================")
                print("FINAL DISTRIBUTION:")

                print(
                    df_final[label_col]
                    .value_counts()
                    .sort_index()
                )

                print(
                    f"\nTotal samples: {len(df_final)}"
                )

            return (
                df_final
                .sample(
                    frac=1,
                    random_state=self.random_state
                )
                .reset_index(drop=True)
            )

        return df.copy()

"""# Median imputation"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Median/Median/train_median.parquet"
LABEL_COL = "label_3"

df_median = pd.read_parquet(INPUT_FILE)
print(f"Đã đọc file: {df_median.shape}")
df_median

print(f"Phân bố label trước SMOTified GAN:")
print(df_median[LABEL_COL].value_counts().sort_index())

smotified_gan = SMOTifiedGAN(verbose=True, random_state=42)

df_balanced = smotified_gan.fit_resample(df_median, label_col="label_3", epochs=50, batch_size=512)

print(f"\nPhân bố label sau SMOTified GAN:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_median[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC SMOTified-GAN", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU SMOTified-GAN", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label - SMOTified-GAN", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_median_smotified_gan.parquet", index=False)

"""# Mean imoutation"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Mean/Mean/train_mean.parquet"
LABEL_COL = "label_3"

df_mean = pd.read_parquet(INPUT_FILE)
print(f"Đã đọc file: {df_mean.shape}")
df_mean

print(f"Phân bố label trước SMOTified GAN:")
print(df_mean[LABEL_COL].value_counts().sort_index())

smotified_gan = SMOTifiedGAN(verbose=True, random_state=42)

df_balanced = smotified_gan.fit_resample(df_mean, label_col="label_3", epochs=50, batch_size=512)

print(f"\nPhân bố label sau SMOTified GAN:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_mean[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC SMOTified-GAN", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU SMOTified-GAN", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label - SMOTified-GAN", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_mean_smotified_gan.parquet", index=False)

"""# Extra_trees imputation"""

INPUT_FILE = "/kaggle/input/datasets/anhtran10/lo-dataset/Extra_trees/Extra_trees/train_extra.parquet"
LABEL_COL = "label_3"

df_Extra_trees = pd.read_parquet(INPUT_FILE)
print(f"Đã đọc file: {df_Extra_trees.shape}")
df_Extra_trees

print(f"Phân bố label trước SMOTified GAN:")
print(df_Extra_trees[LABEL_COL].value_counts().sort_index())

smotified_gan = SMOTifiedGAN(verbose=True, random_state=42)

df_balanced = smotified_gan.fit_resample(df_Extra_trees, label_col="label_3", epochs=50, batch_size=512)

print(f"\nPhân bố label sau SMOTified GAN:")
print(df_balanced[LABEL_COL].value_counts().sort_index())

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
df_Extra_trees[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="TRƯỚC SMOTified-GAN", color='red')
plt.xticks(rotation=45)

plt.subplot(1,2,2)
df_balanced[LABEL_COL].value_counts().sort_index().plot(kind='bar', title="SAU SMOTified-GAN", color='green')
plt.xticks(rotation=45)

plt.suptitle("So sánh phân bố label - SMOTified-GAN", fontsize=14)
plt.tight_layout()
plt.show()

df_balanced.to_parquet("train_Extra_trees_smotified_gan.parquet", index=False)